# Site
title:               Arya NK
bio:                'Software Developer'
description:        '•Data Science •Machine Learning •Data Visualisation'
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://arya-nk.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   arya-nk

# Social
# if you don't have any of social below, comment the line.
google:
  #plus:            #username
  analytics:        UA-114322052-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
#twitter:           username
facebook:           arya.nk.moon
github-url:         Arya-NK
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           aryanalinkumar
#xing:              username
instagram:          arya_nalinkumar
#lastfm:            username
#tumblr:            username
medium:             '@aryank'
#pinterest:         username
#foursquare:        username
#steam:             username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: /Arya_NK

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
